import type { Config } from "tailwindcss";

const colorScale = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const palette = [
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
];

const spacing = [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 72, 80, 96];

const safeClasses = [
  "container",
  "mx-auto",
  "px-4",
  "px-5",
  "px-6",
  "py-2",
  "py-3",
  "py-4",
  "py-5",
  "py-6",
  "py-8",
  "py-10",
  "py-12",
  "pt-4",
  "pt-6",
  "pb-4",
  "pb-6",
  "pb-8",
  "gap-1",
  "gap-1.5",
  "gap-2",
  "gap-3",
  "gap-4",
  "gap-5",
  "gap-6",
  "grid",
  "flex",
  "inline-flex",
  "items-center",
  "justify-center",
  "justify-between",
  "justify-start",
  "justify-end",
  "self-start",
  "self-center",
  "w-full",
  "w-auto",
  "h-full",
  "h-screen",
  "min-h-screen",
  "overflow-hidden",
  "overflow-auto",
  "overflow-y-auto",
  "rounded",
  "rounded-sm",
  "rounded-md",
  "rounded-lg",
  "rounded-xl",
  "rounded-2xl",
  "rounded-3xl",
  "border",
  "border-0",
  "border-t",
  "border-b",
  "border-l",
  "border-r",
  "shadow-sm",
  "shadow",
  "shadow-lg",
  "shadow-xl",
  "shadow-2xl",
  "backdrop-blur",
  "backdrop-blur-md",
  "backdrop-blur-xl",
  "transition",
  "transition-all",
  "duration-150",
  "duration-200",
  "duration-300",
  "ease-out",
  "ease-in-out",
  "relative",
  "absolute",
  "fixed",
  "sticky",
  "inset-0",
  "text-left",
  "text-center",
  "text-right",
  "whitespace-nowrap",
  "break-words",
  "truncate",
  "select-none",
  "cursor-pointer",
  "cursor-not-allowed",
  "uppercase",
  "tracking-wide",
  "tracking-wider",
  "tracking-[0.15em]",
  "font-medium",
  "font-semibold",
  "font-bold",
  "leading-none",
  "leading-tight",
  "leading-relaxed",
];

const colorClasses = palette.flatMap((color) =>
  colorScale.flatMap((shade) => [
    `bg-${color}-${shade}`,
    `text-${color}-${shade}`,
    `border-${color}-${shade}`,
    `ring-${color}-${shade}`,
    `from-${color}-${shade}`,
    `via-${color}-${shade}`,
    `to-${color}-${shade}`,
  ]),
);

const opacityClasses = palette.flatMap((color) =>
  [5, 10, 15, 20, 25, 30, 40, 50, 60].flatMap((opacity) => [
    `bg-${color}-500/${opacity}`,
    `text-${color}-400/${opacity}`,
    `border-${color}-500/${opacity}`,
  ]),
);

const spacingClasses = spacing.flatMap((value) => [
  `p-${value}`,
  `px-${value}`,
  `py-${value}`,
  `pt-${value}`,
  `pr-${value}`,
  `pb-${value}`,
  `pl-${value}`,
  `m-${value}`,
  `mx-${value}`,
  `my-${value}`,
  `gap-${value}`,
  `w-${value}`,
  `h-${value}`,
  `min-w-${value}`,
  `min-h-${value}`,
  `max-w-${value}`,
  `max-h-${value}`,
]);

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    ...safeClasses,
    ...colorClasses,
    ...opacityClasses,
    ...spacingClasses,
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontWeight: {
        "500": "500",
        "600": "600",
        "700": "700",
        "800": "800",
      },
      colors: {
        background: "var(--bg-base)",
        foreground: "var(--text-primary)",
        accent: {
          from: "var(--accent-from)",
          to:   "var(--accent-to)",
        },
      },
      animation: {
        "gradient-shift": "gradient-shift 3s ease infinite",
        "pulse-glow":     "pulse-glow 2s ease-in-out infinite",
        "fade-in-up":     "fade-in-up 0.4s ease both",
        "fade-in":        "fade-in 0.3s ease both",
        "slide-in-left":  "slide-in-left 0.35s ease both",
        "spin-slow":      "spin-slow 3s linear infinite",
      },
    },
  },
  plugins: [],
};
export default config;
